name: Lint and Test
run-name: ${{ github.actor }} is running lint and tester
on: 
  pull_request:
    branches: ["*"]
    paths-ignore: ["**.md"]
  workflow_dispatch:
        
jobs:
  lint-and-test:
    name: Lint & Test project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          # Install a specific version of uv.
          version: "0.9.26"
      - run: uvx ruff check
      - run: uvx --with pytest-custom-exit-code pytest --suppress-no-test-exit-code
